name = "thotlab-landingpage"
compatibility_date = "2023-12-18"
pages_build_output_dir = "dist"

[env.production]
name = "thotlab-landingpage"

# Variables de entorno para el despliegue
[vars]
NODE_ENV = "production"

# Configuración para variables de entorno sensibles
# Estas se configurarán desde el dashboard de Cloudflare
# VITE_EMAILJS_SERVICE_ID
# VITE_EMAILJS_PUBLIC_KEY  
# VITE_EMAILJS_TEMPLATE_ID
